### ISSUE TITLE
Missing --load option in sepolicy-inject

### ISSUE THREAD

**Issue by xmikos** [pasis/setools-android#1]
Thanks for your great work, I have finally merged your updates to my [xmikos/setools-android](https://github.com/xmikos/setools-android) repo. But I have also noticed that you didn't ported my `--load` option in `sepolicy-inject`, so I have ported it myself and made new release 1.3. If you want to merge my changes back to your repo (so we don't diverge), it would be great :-)

**Comment by pasis** [comment]
Merged. Must be I missed commit where you added `--load`. I copied new sepolicy-inject as it was and tried to port all changes back.
